### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by BillZhucn** [bob7l/Clearlag-Languages#3]
Could you tell me which can be translated and which cannot be? Thank you.

**Comment by bob7l** [comment]
Anything that begins with a # is ignored.

The path cannot be translated (Ex: command.admin.name cannot be changed)

The replaced tag surrounded by {} CAN be replaced. Although there's not really any point in doing so unless someone who know English wants to customize their language file. 

Everything after the "=" CAN be changed. This includes command NAMES (Not /lagg admin <argument>). So you can change /lagg clear, to /lagg removeAll. Although the permissions will still use the original command names. So "removeAll" would still use lagg.clear as a permission even though you changed it. 

Lastly, you can change single lines to multi-lines using brackets.
