### ISSUE TITLE
Clear directly after death very frustrating...

### ISSUE THREAD

**Issue by AlexBrightwater** [bob7l/Clearlag-Languages#47]
I am running a small SMP Server. And in the first minutes of players online, someone died and lost all their Items because a second later, they got purged...
So I am asking for a feature, that if enabled would prevent ClearLag from purging all items for a configurable time after the death. Or If this is possible just not purge the items of the person who just died. Ie only purging stuff older than x time.

**Comment by Nick-vdM** [comment]
Have you tried [save death drops](https://dev.bukkit.org/projects/clearlag-savedeathdrops)
