### ISSUE TITLE
How do I switch plugin language?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [bob7l/Clearlag-Languages#6]
I didn't found the config option about "lang" or "language" or "en" or "en-us", etc.

**Comment by bob7l** [comment]
# -- 'language' Clearlag supports multiple languages (English, Spanish, Japanese) translated by the community
settings:
  language: Japanese

(English, Spanish, Japanese)

If you want to use a custom language, either edit one of those, or add it under /languages inside the Clearlag jar

**Comment by mhtvsSFrpHdE** [comment]
got it, so there isn't a "switch" like `language: en-us` instead, we replace the entire file.

**Comment by bob7l** [comment]
If you want a custom language file, then you have the option to do that, yes. 
If you want to use one of the languages provided, you have (English, Spanish, Japanese).

Example:
language: Spanish

It's just the name of the file.

**Comment by mhtvsSFrpHdE** [comment]
@bob7l So that how it is!  
The language option didn't auto generate and I need to add it manually.  
Thank you!
