### ISSUE TITLE
Modification of the Configuration

### ISSUE THREAD

**Issue by GoldFrite** [bob7l/Clearlag-Languages#8]
**Hello
I wanted to change the configuration of the plug in, for example, by modifying the warning message. Except that, after having modified in the "Config.yml" file, there is no difference in the game ...
Sorry for the bad English, I speak French (and I wanted to translate the warning message into French).**

**Eg:** 
Config:
![image](https://user-images.githubusercontent.com/61522145/76143646-7779c600-6079-11ea-897d-df5544115213.png)

In game:
![image](https://user-images.githubusercontent.com/61522145/76143669-a3954700-6079-11ea-82b1-8e3b4cedab2b.png)

**Thank**

**Comment by GoldFrite** [comment]
Help please !

**Comment by bob7l** [comment]
If Clearlag isn't reading your config, that means it contains an error. Either check your logs for an error, or use this program to hopefully find the issue: https://yaml-online-parser.appspot.com/

**Comment by GoldFrite** [comment]
Okay, thank !

**Comment by GoldFrite** [comment]
```yaml
ERROR:

while parsing a block mapping
  in "<unicode string>", line 259, column 3:
      enabled: true
      ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 261, column 63:
     ... &r[&4ClearLag&r] &cLe serveur n'est plus surchargé !'
                                         ^
```

**Comment by GoldFrite** [comment]
Its good ! the problem was an apostrophe !
